server:
  port: 7070

keycloak:
  username: admin
  password: admin
  realm: master
  uri: http://localhost:18080/auth
  auth-server-url: http://localhost:18080/auth/realms/master/protocol/openid-connect/auth

springdoc:
  swagger-ui:
    oauth:
      clientId: camunda-identity
      clientSecret: HnKx4i4Mv8cBRIoFyznllf5SzyqMeuyj

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/master
          jwk-set-uri: http://localhost:18080/auth/realms/master/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/auth/realms/master

jwt:
  auth:
    converter:
      resource-id: camunda-identity
      principle_attribute: preferred_username