server:
  port: 7070
spring:
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:18080/auth/realms/Keycloak_Realm
          jwk-set-uri: http://host.docker.internal:18080/auth/realms/Keycloak_Realm/protocol/openid-connect/certs

module-name: mymodule
api-version: 1.0z

springdoc:
  swagger-ui:
    oauth:
      clientId: swagger-test
      clientSecret: vigneshbala
  oAuthFlow:
    authorizationUrl: http://lhost.docker.internal:18080/auth/realms/Keycloak_Realm/protocol/openid-connect/auth
    tokenUrl: http://host.docker.internal:18080/auth/realms/Keycloak_Realm/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true